### ISSUE TITLE
Data loading produces server error

### ISSUE THREAD

**Issue by mhuelfen** [lukestokes/eos-playground#2]
The download oft the latest data fail, since today. 

Starting the script I get:

```
Welcome to the EOS Knights Stats Machine!
Starting up at 11:11:45 14.11.2018
Loading data from data.json...
We have data on 5247 accounts at block number 26439034 using sequence number 7789837
{ Error: {"errors":{"producer":"The request to the producer API failed"}}
    at //eosknights/node_modules/eosjs-api/lib/apigen.js:112:23
    at process.internalTickCallback (internal/process/next_tick.js:77:7) status: 500, statusText: 'Internal Server Error' }
```

Before that download the data was working but crashed often, with this error:

```
Updating: block number 26437466 at 2018-11-11T20:58:15.500 account sequence 7789103
{ Error: <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>

    at //eosknights/node_modules/eosjs-api/lib/apigen.js:112:23
    at process.internalTickCallback (internal/process/next_tick.js:77:7) status: 504, statusText: 'Gateway Time-out' }
```

**Comment by lukestokes** [comment]
Yeah, I've been noticing this also. Unfortunately, it seems the greymass API (which appears to be one of the few node still running the full deprecated history plugin) is crashing (the HTTP 500 series errors are server-side errors).

I may adjust my code to just query the revenue table, but that kind of defeats the purpose of externally validated data by going through each transaction. You can look up the revenue table on blocs.io right now in the mean time:

![image](https://user-images.githubusercontent.com/344748/48507777-7f717f00-e812-11e8-8405-030abe59bef5.png)
